export { BuyICTDashboard } from './BuyICTDashboard'
export { Opportunities } from './Opportunities'
export { Contacts } from './Contacts'
export { DepartmentMappings } from './DepartmentMappings'
export { Settings } from './Settings'
export { OpportunityDetail } from './OpportunityDetail'
export { default as Organisations } from './Organisations'
export { default as OrganisationDetail } from './OrganisationDetail'
