-- Disable RLS on all tables for development
ALTER TABLE spaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE space_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE prompt_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE brand_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE brand_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
